import { instantiate, layout, mutNumerator } from '../core.ts';
import type { EpochBatchExecution } from '../execution.ts';
import type { GpuAdapterIdentity } from '../protocol.ts';
import { SoupMetrics, type EpochStats, type Metrics, type SoupConfig } from '../soup.ts';
import {
  GpuBench,
  MAX_RESIDENT_EPOCH_BATCH,
  type ResidentCounters,
  type ResidentEpochRunner,
} from './gpu.ts';

const PRODUCTION_CHUNK_STEPS = 2048;
const PRODUCTION_WORKGROUP_SIZE = 128;

/**
 * Reusable CuBFF epoch-zero initializer for this coordinator module.
 *
 * Every call reapplies tape length and seed before filling the requested
 * population, so a previous run cannot affect the generated bytes. The Wasm
 * instance is used only for CuBFF's pinned initializer; all epoch evaluation
 * remains in the independent WGSL implementation.
 */
class CuBffPopulationInitializer {
  private readonly core = instantiate('cubff');

  initialize(cfg: SoupConfig): Uint8Array {
    if (cfg.engine !== 'cubff') throw new Error('WebGPU execution supports CuBFF only');
    this.core.configure(cfg.tapeLen);
    const mem = layout(this.core, cfg.nTapes, cfg.tapeLen);
    this.core.set_seed(BigInt(cfg.seed >>> 0));
    this.core.initialize(mem.soup, cfg.nTapes);
    return new Uint8Array(
      this.core.memory.buffer,
      mem.soup,
      cfg.nTapes * cfg.tapeLen,
    ).slice();
  }
}

let populationInitializer: CuBffPopulationInitializer | null = null;

function initializePopulation(cfg: SoupConfig): Uint8Array {
  populationInitializer ??= new CuBffPopulationInitializer();
  return populationInitializer.initialize(cfg);
}

/** Complete CuBFF epoch execution with an authoritative GPU-resident population. */
export class WebGpuCuBffSoup implements EpochBatchExecution {
  cfg: SoupConfig;
  data: Uint8Array;
  epoch = 0;
  readonly computePath = 'webgpu' as const;
  readonly maxEpochBatch = MAX_RESIDENT_EPOCH_BATCH;
  readonly gpuAdapter: GpuAdapterIdentity;
  readonly workerCount = 0;
  readonly coreDescription: string;

  private readonly context: GpuBench;
  private runner: ResidentEpochRunner;
  private readonly metrics = new SoupMetrics();
  private disposed = false;

  private constructor(
    context: GpuBench,
    cfg: SoupConfig,
    data: Uint8Array,
    runner: ResidentEpochRunner,
  ) {
    this.context = context;
    this.cfg = { ...cfg };
    this.data = data;
    this.runner = runner;
    this.gpuAdapter = {
      vendor: context.info.vendor,
      architecture: context.info.architecture,
      device: context.info.device,
      description: context.info.description,
      isFallbackAdapter: context.info.isFallbackAdapter,
    };
    const label = [context.info.vendor, context.info.architecture, context.info.device]
      .filter((part) => part && part !== 'unknown')
      .join(' ');
    this.coreDescription = label ? `cubff webgpu ${label}` : 'cubff webgpu';
  }

  static async create(context: GpuBench, cfg: SoupConfig): Promise<WebGpuCuBffSoup> {
    if (cfg.engine !== 'cubff') throw new Error('WebGPU execution supports CuBFF only');
    const data = initializePopulation(cfg);
    const runner = await context.createResidentEpochRunner(
      cfg.nTapes,
      cfg.tapeLen,
      cfg.maxSteps,
      PRODUCTION_CHUNK_STEPS,
      'storage',
      PRODUCTION_WORKGROUP_SIZE,
    );
    try {
      runner.uploadPopulation(data);
      return new WebGpuCuBffSoup(context, cfg, data, runner);
    } catch (error) {
      runner.destroy();
      throw error;
    }
  }

  async runEpoch(): Promise<EpochStats> {
    return (await this.runEpochBatch(1))[0];
  }

  async runEpochBatch(count: number): Promise<EpochStats[]> {
    this.assertAvailable();
    if (!Number.isInteger(count) || count < 1 || count > this.maxEpochBatch) {
      throw new Error(`invalid WebGPU epoch batch size ${count}`);
    }
    const started = performance.now();
    const counterBatch = await this.runner.runEpochBatch(
      BigInt(this.epoch),
      count,
      mutNumerator(this.cfg.mutationRate),
      BigInt(this.cfg.seed >>> 0),
    );
    const elapsedPerEpoch = (performance.now() - started) / count;
    const execs = this.cfg.nTapes >> 1;
    const stats = counterBatch.map((counters) =>
      this.epochStats(counters, execs, elapsedPerEpoch),
    );
    this.epoch += count;
    return stats;
  }

  private epochStats(
    counters: ResidentCounters,
    execs: number,
    elapsedMs: number,
  ): EpochStats {
    const haltTotal = counters.halts[0] + counters.halts[1] + counters.halts[2];
    if (haltTotal !== execs) {
      throw new Error(`WebGPU epoch returned ${haltTotal} halt results for ${execs} pairs`);
    }
    const halts = [0, counters.halts[0], counters.halts[1], 0, counters.halts[2]];
    return {
      execs,
      steps: counters.ops,
      meanSteps: execs ? counters.ops / execs : 0,
      halts,
      ms: elapsedMs,
    };
  }

  async readPopulation(): Promise<Uint8Array> {
    this.assertAvailable();
    const snapshot = await this.runner.readSnapshot();
    this.data = snapshot.population;
    return this.data;
  }

  computeMetrics(): Metrics {
    return this.metrics.compute(this.cfg, this.data);
  }

  async reshape(cfg: SoupConfig): Promise<void> {
    this.assertAvailable();
    if (cfg.engine !== 'cubff') throw new Error('WebGPU execution supports CuBFF only');
    if (cfg.nTapes !== this.cfg.nTapes || cfg.tapeLen !== this.cfg.tapeLen) {
      throw new Error('WebGPU shape changes require a new run');
    }
    if (cfg.maxSteps !== this.cfg.maxSteps) {
      const population = await this.readPopulation();
      const replacement = await this.context.createResidentEpochRunner(
        cfg.nTapes,
        cfg.tapeLen,
        cfg.maxSteps,
        PRODUCTION_CHUNK_STEPS,
        'storage',
        PRODUCTION_WORKGROUP_SIZE,
      );
      try {
        replacement.uploadPopulation(population);
      } catch (error) {
        replacement.destroy();
        throw error;
      }
      this.runner.destroy();
      this.runner = replacement;
    }
    this.cfg = { ...cfg };
  }

  randomize(): void {
    this.assertAvailable();
    this.data = initializePopulation(this.cfg);
    this.runner.uploadPopulation(this.data);
    this.epoch = 0;
  }

  dispose(): void {
    if (this.disposed) return;
    this.disposed = true;
    this.runner.destroy();
  }

  private assertAvailable(): void {
    if (this.disposed) throw new Error('WebGPU run is unavailable');
  }
}
