// Compile the independent CuBFF and Brainfuck-Life population cores and the
// paper's exact Brotli measurement encoder to embedded Wasm modules. Embedding
// keeps worker startup independent of fetch paths.
//
// Needs zig on PATH for the wasm32 target: `brew install zig`. Apple's clang
// is not built with it.
import { execFileSync } from 'node:child_process';
import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const nativeRoot = join(repoRoot, 'engine', 'native');
const engineSourceRoot = join(repoRoot, 'engine', 'src');

const CORE_EXPORTS = [
  'configure',
  'set_seed',
  'initialize',
  'evaluate',
  'last_halt',
  'shuffle',
  'run_epoch',
  'run_packed',
  '__heap_base',
];

const BRAINFUCK_LIFE_EXPORTS = [...CORE_EXPORTS, 'mutate_soup'];

const dir = mkdtempSync(join(tmpdir(), 'clr-wasm-'));
const zigGlobalCache = join(dir, 'zig-global-cache');
const zigLocalCache = join(dir, 'zig-local-cache');
mkdirSync(zigGlobalCache);
mkdirSync(zigLocalCache);
const zigEnv = {
  ...process.env,
  ZIG_GLOBAL_CACHE_DIR: zigGlobalCache,
  ZIG_LOCAL_CACHE_DIR: zigLocalCache,
};
const cubffOut = join(dir, 'cubff.wasm');
const brainfuckLifeOut = join(dir, 'brainfuck-life.wasm');
const brotliOut = join(dir, 'brotli.wasm');

function cSources(path) {
  return readdirSync(path)
    .filter((name) => name.endsWith('.c'))
    .sort()
    .map((name) => join(path, name));
}

try {
  const compileCore = (source, output, exports) =>
    execFileSync(
      'zig',
      [
        'cc',
        '-target',
        'wasm32-freestanding',
        '-nostdlib',
        '-O3',
        '-Wl,--no-entry',
        '-Wl,--export-memory',
        ...exports.map((e) => `-Wl,--export=${e}`),
        '-o',
        output,
        source,
      ],
      {
        env: zigEnv,
        stdio: ['ignore', 'inherit', 'inherit'],
      },
    );

  compileCore(join(nativeRoot, 'cubff_soup.c'), cubffOut, CORE_EXPORTS);
  compileCore(
    join(nativeRoot, 'brainfuck_life_soup.c'),
    brainfuckLifeOut,
    BRAINFUCK_LIFE_EXPORTS,
  );

  const vendor = join(nativeRoot, 'vendor', 'brotli', 'c');
  execFileSync(
    'zig',
    [
      'cc',
      '-target',
      'wasm32-wasi',
      '-mexec-model=reactor',
      '-O3',
      `-I${join(vendor, 'include')}`,
      `-I${join(vendor, 'common')}`,
      `-I${join(vendor, 'enc')}`,
      '-Wl,--export-memory',
      '-Wl,--export=brotli_compress',
      '-Wl,--export=brotli_max_compressed_size',
      '-Wl,--export=__heap_base',
      '-Wl,--strip-all',
      '-o',
      brotliOut,
      join(nativeRoot, 'brotli_bridge.c'),
      ...cSources(join(vendor, 'common')),
      ...cSources(join(vendor, 'enc')),
    ],
    {
      env: zigEnv,
      stdio: ['ignore', 'inherit', 'inherit'],
    },
  );
} catch (e) {
  if (e.code === 'ENOENT') {
    console.error(
      '\nzig not found. The Wasm cores are compiled from engine/native/cubff_soup.c ' +
        'and engine/native/brainfuck_life_soup.c:\n  brew install zig\n',
    );
  }
  rmSync(dir, { recursive: true, force: true });
  process.exit(1);
}

const cubff = readFileSync(cubffOut);
const brainfuckLife = readFileSync(brainfuckLifeOut);
const brotli = readFileSync(brotliOut);
rmSync(dir, { recursive: true, force: true });

writeFileSync(
  join(engineSourceRoot, 'cubff.wasm.ts'),
  `/* generated by tools/build-wasm.mjs from engine/native/cubff_soup.c — do not edit\n` +
    ` * SPDX-License-Identifier: Apache-2.0 */\n` +
    `export const CUBFF_WASM_B64 =\n  '${cubff.toString('base64')}';\n`,
);

writeFileSync(
  join(engineSourceRoot, 'brainfuckLife.wasm.ts'),
  `/* generated by tools/build-wasm.mjs from engine/native/brainfuck_life_soup.c — do not edit\n` +
    ` * SPDX-License-Identifier: GPL-3.0-or-later */\n` +
    `export const BRAINFUCK_LIFE_WASM_B64 =\n  '${brainfuckLife.toString('base64')}';\n`,
);

writeFileSync(
  join(engineSourceRoot, 'brotli.wasm.ts'),
  `/* generated by tools/build-wasm.mjs from Brotli 1.1.0 — do not edit\n` +
    ` * SPDX-License-Identifier: MIT */\n` +
    `export const BROTLI_WASM_B64 =\n  '${brotli.toString('base64')}';\n`,
);

console.log(`engine/native/cubff_soup.c: ${cubff.length} bytes -> engine/src/cubff.wasm.ts`);
console.log(
  `engine/native/brainfuck_life_soup.c: ${brainfuckLife.length} bytes -> ` +
    'engine/src/brainfuckLife.wasm.ts',
);
console.log(`Brotli 1.1.0: ${brotli.length} bytes -> engine/src/brotli.wasm.ts`);
